[env:gamebuino_aka]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 16MB
board_build.psram_type = opi
lib_deps =
    https://github.com/jmp42/Gamebuino_AKA_lib
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
upload_protocol = esptool
